# Generated by Django 4.0.4 on 2022-06-21 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_task_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 14, 12, 17, 323021)),
        ),
    ]
