# Generated by Django 4.0.4 on 2022-06-16 09:41

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
