# Generated by Django 4.0.4 on 2022-06-23 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_profile_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pin', models.IntegerField()),
            ],
        ),
    ]
